### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by KennyGoi** [pillarjs/parseurl#10]
**Affected files**:
parseurl/index.js
`66: var url = req.originalUrl`

parseurl/index.js
`81: parsed = fastparse(url)`

parseurl/index.js
`95: function fastparse (str) {`

parseurl/index.js
`107: for (var i = 1; i < str.length; i++) {`

parseurl/index.js
`36: var url = req.url`

parseurl/index.js
`51: parsed = fastparse(url)`

parseurl/index.js
`95: function fastparse (str) {`

parseurl/index.js
`107: for (var i = 1; i < str.length; i++) {`

**Risks**:
An attacker could provide a very high loop iteration count, causing the loop to go on for prolonged periods of time, potentially causing the application to stop responding. Additionally, if the operation inside the loop is tied to some exhaustible functionality, it may cause bloat elsewhere; For example - if file writes occur inside the loop, then an attacker can cause that file to bloat by simply engaging this file writing capability a very high amount of times.

The application relied on a user-provided value to determine the number of iterations performed by a loop, without enforcing a limited range for this value.

**Comment by import-brain** [comment]
A time complexity attack?

This looks pretty important, @dougwilson, could you please take a look? Thanks!

**Comment by dougwilson** [comment]
Thanks, I don't know why I am not getting any of the issues cretaed by this user. @KennyGoi please report potential security iasues following http://expressjs.com/en/resources/contributing.html#security-policies-and-procedures
